"""
README Generator - Generates comprehensive documentation with code flow diagrams
"""

from typing import Dict, List, Optional
from pathlib import Path
import ast


class ReadmeGenerator:
    """Generates README.md with code structure and flow diagrams"""

    def __init__(self, project_path: str, analysis_results: Dict):
        """
        Initialize README Generator

        Args:
            project_path: Path to the project
            analysis_results: Complete analysis results from CodePulseAnalyzer
        """
        self.project_path = Path(project_path)
        self.results = analysis_results
        self.file_metrics = analysis_results.get('file_metrics', {})
        self.health = analysis_results.get('health', {})
        self.personality = analysis_results.get('personality', {})

    def generate_full_readme(self) -> str:
        """
        Generate complete README with all sections

        Returns:
            Complete README markdown
        """
        sections = []

        # Header
        sections.append(self._generate_header())

        # Overview
        sections.append(self._generate_overview())

        # Health & Quality
        sections.append(self._generate_health_section())

        # Architecture
        sections.append(self._generate_architecture())

        # Project Structure
        sections.append(self._generate_structure())

        # Code Flow Diagrams
        sections.append(self._generate_flow_diagrams())

        # Module Documentation
        sections.append(self._generate_module_docs())

        # Getting Started
        sections.append(self._generate_getting_started())

        # Contributing
        sections.append(self._generate_contributing())

        return '\n\n'.join(sections)

    def generate_file_readme(self, file_path: str) -> str:
        """
        Generate README for a specific file

        Args:
            file_path: Relative path to file

        Returns:
            File-specific README
        """
        sections = []

        # Header
        sections.append(f"# 📄 {Path(file_path).name}")
        sections.append(f"**File:** `{file_path}`")

        # File analysis
        sections.append(self._generate_file_analysis(file_path))

        # Code structure
        sections.append(self._generate_file_structure(file_path))

        # Function flow
        sections.append(self._generate_file_flow(file_path))

        return '\n\n'.join(sections)

    def _generate_header(self) -> str:
        """Generate README header"""
        project_name = self.project_path.name.replace('_', ' ').replace('-', ' ').title()

        return f"""# {project_name}

> 📊 Generated by [CodePulse](https://github.com/yourusername/codepulse)
>
> 📅 Generated: {self.results.get('analysis_timestamp', 'N/A')[:10]}

[![Health Score](https://img.shields.io/badge/Health_Score-{self.health.get('overall_score', 0):.0f}%25-{self._get_badge_color(self.health.get('overall_score', 0))})](https://github.com)
[![Code Lines](https://img.shields.io/badge/Code_Lines-{self.file_metrics.get('code_lines', 0):,}-blue)](https://github.com)
[![Files](https://img.shields.io/badge/Files-{self.file_metrics.get('total_files', 0)}-green)](https://github.com)"""

    def _generate_overview(self) -> str:
        """Generate project overview"""
        personality = self.personality.get('personality', 'Unknown')
        description = self.personality.get('description', '')

        return f"""## 📋 Overview

**Project Type:** {personality}

{description}

### Quick Stats

| Metric | Value |
|--------|-------|
| **Health Score** | {self.health.get('overall_score', 0):.1f}/100 ({self.health.get('rating', 'N/A').upper()}) |
| **Total Files** | {self.file_metrics.get('total_files', 0)} |
| **Lines of Code** | {self.file_metrics.get('code_lines', 0):,} |
| **Languages** | {', '.join(self.file_metrics.get('language_stats', {}).keys())} |
| **Personality** | {personality} |"""

    def _generate_health_section(self) -> str:
        """Generate health & quality section"""
        components = self.health.get('components', {})

        bars = []
        for name, data in components.items():
            score = data.get('score', 0)
            filled = int(score / 5)
            bar = '█' * filled + '░' * (20 - filled)
            bars.append(f"**{name.replace('_', ' ').title()}**: `{bar}` {score:.1f}/100")

        health_bars = '\n'.join(bars)

        insights = self.results.get('insights', [])
        insight_list = '\n'.join([f"- {insight}" for insight in insights[:5]])

        return f"""## 💊 Code Health

### Health Components

{health_bars}

### Key Insights

{insight_list}"""

    def _generate_architecture(self) -> str:
        """Generate architecture diagram"""
        lang_stats = self.file_metrics.get('language_stats', {})

        # Create directory structure diagram
        files = self.file_metrics.get('files', [])

        # Build tree
        tree_lines = []
        dirs = {}
        for file_info in files:
            path = Path(file_info['path'])
            if len(path.parts) > 1:
                dir_name = path.parts[0]
                if dir_name not in dirs:
                    dirs[dir_name] = []
                dirs[dir_name].append(path.name)

        # Create mermaid diagram
        mermaid_graph = """```mermaid
graph TD
    Root[Project Root]
"""

        for i, (dir_name, files_in_dir) in enumerate(dirs.items()):
            mermaid_graph += f"    Root --> Dir{i}[{dir_name}/]\n"
            for j, file in enumerate(files_in_dir[:5]):  # Limit to 5 files per dir
                mermaid_graph += f"    Dir{i} --> File{i}_{j}[{file}]\n"
            if len(files_in_dir) > 5:
                mermaid_graph += f"    Dir{i} --> More{i}[...{len(files_in_dir) - 5} more]\n"

        mermaid_graph += "```"

        return f"""## 🏗️ Architecture

### Project Structure

{mermaid_graph}

### Language Distribution

```mermaid
pie title "Code Distribution"
{self._generate_pie_chart_data(lang_stats)}
```"""

    def _generate_structure(self) -> str:
        """Generate project structure tree"""
        files = self.file_metrics.get('files', [])

        # Build tree structure
        tree = "```\n"
        tree += f"{self.project_path.name}/\n"

        # Group by directory
        dirs = {}
        for file_info in files[:30]:  # Limit to 30 files
            path = Path(file_info['path'])
            if len(path.parts) > 1:
                dir_name = str(path.parent)
                if dir_name not in dirs:
                    dirs[dir_name] = []
                dirs[dir_name].append({
                    'name': path.name,
                    'lines': file_info['lines']['code'],
                    'language': file_info['language']
                })
            else:
                if '.' not in dirs:
                    dirs['.'] = []
                dirs['.'].append({
                    'name': path.name,
                    'lines': file_info['lines']['code'],
                    'language': file_info['language']
                })

        # Print tree
        for dir_name in sorted(dirs.keys()):
            if dir_name != '.':
                tree += f"├── {dir_name}/\n"
                for file_info in dirs[dir_name]:
                    tree += f"│   ├── {file_info['name']} ({file_info['lines']} lines, {file_info['language']})\n"

        # Root files
        if '.' in dirs:
            for file_info in dirs['.']:
                tree += f"├── {file_info['name']} ({file_info['lines']} lines, {file_info['language']})\n"

        tree += "```"

        return f"""## 📁 Project Structure

{tree}

**Total:** {self.file_metrics.get('total_files', 0)} files, {self.file_metrics.get('code_lines', 0):,} lines of code"""

    def _generate_flow_diagrams(self) -> str:
        """Generate code flow diagrams"""

        # Main application flow
        flow_diagram = """## 🔄 Code Flow

### Main Application Flow

```mermaid
sequenceDiagram
    participant User
    participant App
    participant Module1
    participant Database

    User->>App: Initialize
    App->>Module1: Load Configuration
    Module1->>Database: Connect
    Database-->>Module1: Connection OK
    Module1-->>App: Ready
    App-->>User: Application Started

    User->>App: Request Data
    App->>Database: Query
    Database-->>App: Results
    App-->>User: Display Results
```

### Component Interaction

```mermaid
graph LR
    A[User Interface] --> B[Business Logic]
    B --> C[Data Layer]
    C --> D[(Database)]
    B --> E[External APIs]
    A --> F[Authentication]
    F --> B
```"""

        return flow_diagram

    def _generate_module_docs(self) -> str:
        """Generate module documentation"""
        files = self.file_metrics.get('files', [])

        module_docs = "## 📚 Module Documentation\n\n"

        # Group by directory
        python_files = [f for f in files if f['language'] == 'Python'][:10]

        for file_info in python_files:
            path = file_info['path']
            lines = file_info['lines']['code']

            module_docs += f"### `{path}`\n\n"
            module_docs += f"- **Lines:** {lines}\n"
            module_docs += f"- **Language:** {file_info['language']}\n"

            # Try to parse and extract info
            try:
                abs_path = self.project_path / path
                if abs_path.exists():
                    with open(abs_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                        tree = ast.parse(content)

                        # Extract docstring
                        docstring = ast.get_docstring(tree)
                        if docstring:
                            module_docs += f"- **Description:** {docstring.split(chr(10))[0]}\n"

                        # Count functions
                        functions = [n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)]
                        if functions:
                            module_docs += f"- **Functions:** {len(functions)}\n"
                            func_list = ', '.join([f.name for f in functions[:5]])
                            module_docs += f"  - {func_list}\n"

                        # Count classes
                        classes = [n for n in ast.walk(tree) if isinstance(n, ast.ClassDef)]
                        if classes:
                            module_docs += f"- **Classes:** {len(classes)}\n"
                            class_list = ', '.join([c.name for c in classes[:5]])
                            module_docs += f"  - {class_list}\n"
            except:
                pass

            module_docs += "\n"

        return module_docs

    def _generate_getting_started(self) -> str:
        """Generate getting started section"""
        return """## 🚀 Getting Started

### Prerequisites

```bash
# Check Python version
python3 --version

# Install dependencies (if requirements.txt exists)
pip install -r requirements.txt
```

### Installation

```bash
# Clone the repository
git clone <repository-url>
cd """ + self.project_path.name + """

# Install dependencies
pip install -r requirements.txt
```

### Usage

```python
# Example usage
from main import App

app = App()
app.run()
```

### Running Tests

```bash
# Run all tests
python -m pytest

# Run specific test
python -m pytest tests/test_app.py
```"""

    def _generate_contributing(self) -> str:
        """Generate contributing section"""
        return f"""## 🤝 Contributing

We welcome contributions! Here's how:

1. **Fork** the repository
2. **Create** a feature branch (`git checkout -b feature/AmazingFeature`)
3. **Commit** your changes (`git commit -m 'Add some AmazingFeature'`)
4. **Push** to the branch (`git push origin feature/AmazingFeature`)
5. **Open** a Pull Request

### Code Quality Standards

This project maintains:
- **Health Score:** {self.health.get('overall_score', 0):.1f}/100
- **Code Style:** {self.personality.get('personality', 'Consistent')}
- **Test Coverage:** Maintained

Please ensure your contributions meet these standards.

## 📄 License

[Add your license here]

## 👥 Team

[Add team members here]

## 📞 Contact

[Add contact information here]

---

**Generated by CodePulse** - Automated Code Analysis & Documentation"""

    def _generate_file_analysis(self, file_path: str) -> str:
        """Generate analysis for specific file"""
        files = self.file_metrics.get('files', [])

        file_info = None
        for f in files:
            if f['path'] == file_path:
                file_info = f
                break

        if not file_info:
            return "**Error:** File not found in analysis"

        return f"""## 📊 File Analysis

| Metric | Value |
|--------|-------|
| **Language** | {file_info['language']} |
| **Total Lines** | {file_info['lines']['total']} |
| **Code Lines** | {file_info['lines']['code']} |
| **Comment Lines** | {file_info['lines']['comments']} |
| **Blank Lines** | {file_info['lines']['blank']} |
| **Size** | {file_info['size']:,} bytes |"""

    def _generate_file_structure(self, file_path: str) -> str:
        """Generate structure diagram for file (all languages)"""
        try:
            abs_path = self.project_path / file_path
            if not abs_path.exists():
                return ""

            # Detect language
            language = abs_path.suffix.lower()

            # Try Python AST first
            if language == '.py':
                try:
                    with open(abs_path, 'r', encoding='utf-8') as f:
                        tree = ast.parse(f.read())

                    structure = "## 🏗️ Code Structure\n\n"

                    # Classes
                    classes = [n for n in ast.walk(tree) if isinstance(n, ast.ClassDef)]
                    if classes:
                        structure += "### Classes\n\n"
                        for cls in classes:
                            structure += f"#### `{cls.name}`\n\n"
                            methods = [n for n in cls.body if isinstance(n, ast.FunctionDef)]
                            if methods:
                                structure += "**Methods:**\n"
                                for method in methods:
                                    args = ', '.join([a.arg for a in method.args.args])
                                    structure += f"- `{method.name}({args})`\n"
                            structure += "\n"

                    # Functions
                    functions = [n for n in tree.body if isinstance(n, ast.FunctionDef)]
                    if functions:
                        structure += "### Functions\n\n"
                        for func in functions:
                            args = ', '.join([a.arg for a in func.args.args])
                            docstring = ast.get_docstring(func)
                            structure += f"#### `{func.name}({args})`\n\n"
                            if docstring:
                                structure += f"{docstring.split(chr(10))[0]}\n\n"

                    return structure
                except:
                    pass

            # Universal structure analysis for all languages
            return self._generate_universal_structure(abs_path)

        except:
            return ""

    def _generate_universal_structure(self, file_path: Path) -> str:
        """Generate detailed structure for any language"""
        try:
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
                lines = content.split('\n')

            structure = "## 🏗️ Code Structure\n\n"
            import re

            # Detect language
            ext = file_path.suffix.lower()
            language_map = {
                '.js': 'JavaScript', '.jsx': 'JavaScript',
                '.ts': 'TypeScript', '.tsx': 'TypeScript',
                '.java': 'Java', '.cpp': 'C++', '.c': 'C',
                '.cs': 'C#', '.go': 'Go', '.rs': 'Rust',
                '.rb': 'Ruby', '.php': 'PHP', '.swift': 'Swift', '.kt': 'Kotlin'
            }
            language = language_map.get(ext, 'Unknown')

            structure += f"**Language:** {language}\n\n"

            # Find imports/dependencies
            imports = self._extract_imports(content, ext)
            if imports:
                structure += "### 📦 Dependencies\n\n"
                for imp in imports[:10]:
                    structure += f"- `{imp}`\n"
                structure += "\n"

            # Find class definitions with details
            class_details = self._extract_classes(content, ext)
            if class_details:
                structure += "### 📋 Classes/Structures\n\n"
                for cls in class_details[:10]:
                    structure += f"#### `{cls['name']}`\n\n"
                    if cls.get('extends'):
                        structure += f"- **Extends:** `{cls['extends']}`\n"
                    if cls.get('methods'):
                        structure += f"- **Methods:** {len(cls['methods'])}\n"
                        for method in cls['methods'][:5]:
                            structure += f"  - `{method}()`\n"
                    structure += "\n"

            # Find function definitions with signatures
            functions = self._extract_functions(content, ext)
            if functions:
                structure += "### 🔧 Functions/Methods\n\n"
                for func in functions[:15]:
                    structure += f"#### `{func['name']}({func['params']})`\n\n"
                    if func.get('return_type'):
                        structure += f"**Returns:** `{func['return_type']}`\n\n"
                    if func.get('description'):
                        structure += f"{func['description']}\n\n"

            # Find constants/variables
            constants = self._extract_constants(content, ext)
            if constants:
                structure += "### 📌 Constants/Variables\n\n"
                for const in constants[:10]:
                    structure += f"- `{const}`\n"
                structure += "\n"

            # Add code statistics
            structure += "### 📊 Code Statistics\n\n"
            structure += f"- **Total Lines:** {len(lines)}\n"
            structure += f"- **Code Lines:** {len([l for l in lines if l.strip() and not l.strip().startswith(('//','#','/*','*'))])}\n"
            structure += f"- **Functions:** {len(functions)}\n"
            structure += f"- **Classes:** {len(class_details)}\n"
            structure += "\n"

            return structure if len(structure) > 100 else ""

        except Exception as e:
            return ""

    def _extract_imports(self, content: str, ext: str) -> list:
        """Extract import/require statements"""
        import re
        imports = []

        patterns = {
            '.js': [r'import\s+.*?from\s+[\'"](.+?)[\'"]', r'require\([\'"](.+?)[\'"]\)'],
            '.ts': [r'import\s+.*?from\s+[\'"](.+?)[\'"]', r'require\([\'"](.+?)[\'"]\)'],
            '.jsx': [r'import\s+.*?from\s+[\'"](.+?)[\'"]'],
            '.tsx': [r'import\s+.*?from\s+[\'"](.+?)[\'"]'],
            '.java': [r'import\s+([\w.]+);'],
            '.go': [r'import\s+"(.+?)"', r'import\s+\((.*?)\)'],
            '.rs': [r'use\s+([\w:]+);'],
            '.rb': [r'require\s+[\'"](.+?)[\'"]'],
            '.php': [r'use\s+([\w\\]+);', r'require\s+[\'"](.+?)[\'"]'],
            '.swift': [r'import\s+(\w+)'],
            '.kt': [r'import\s+([\w.]+)'],
            '.cs': [r'using\s+([\w.]+);'],
            '.cpp': [r'#include\s+[<"](.+?)[>"]'],
            '.c': [r'#include\s+[<"](.+?)[>"]'],
        }

        for pattern in patterns.get(ext, []):
            matches = re.findall(pattern, content, re.MULTILINE | re.DOTALL)
            imports.extend(matches)

        return list(set(imports))[:10]

    def _extract_classes(self, content: str, ext: str) -> list:
        """Extract class definitions with methods"""
        import re
        classes = []

        # Class pattern with optional extends/implements
        class_patterns = {
            '.js': r'class\s+(\w+)(?:\s+extends\s+(\w+))?',
            '.ts': r'(?:export\s+)?class\s+(\w+)(?:\s+extends\s+(\w+))?',
            '.jsx': r'class\s+(\w+)(?:\s+extends\s+(\w+))?',
            '.tsx': r'(?:export\s+)?class\s+(\w+)(?:\s+extends\s+(\w+))?',
            '.java': r'(?:public|private|protected)?\s+class\s+(\w+)(?:\s+extends\s+(\w+))?',
            '.cs': r'(?:public|private|protected)?\s+class\s+(\w+)(?:\s*:\s*(\w+))?',
            '.cpp': r'class\s+(\w+)(?:\s*:\s*(?:public|private|protected)\s+(\w+))?',
            '.swift': r'class\s+(\w+)(?:\s*:\s*(\w+))?',
            '.kt': r'class\s+(\w+)(?:\s*:\s*(\w+))?',
            '.rb': r'class\s+(\w+)(?:\s*<\s*(\w+))?',
            '.php': r'class\s+(\w+)(?:\s+extends\s+(\w+))?',
        }

        pattern = class_patterns.get(ext)
        if pattern:
            matches = re.findall(pattern, content)
            for match in matches:
                class_name = match[0] if isinstance(match, tuple) else match
                extends = match[1] if isinstance(match, tuple) and len(match) > 1 and match[1] else None

                # Find methods in this class
                methods = self._find_methods_in_class(content, class_name, ext)

                classes.append({
                    'name': class_name,
                    'extends': extends,
                    'methods': methods
                })

        return classes

    def _find_methods_in_class(self, content: str, class_name: str, ext: str) -> list:
        """Find methods within a class"""
        import re
        methods = []

        # Simple method detection (can be improved)
        method_patterns = {
            '.js': r'^\s+(\w+)\s*\(',
            '.ts': r'^\s+(?:public|private|protected)?\s*(\w+)\s*\(',
            '.jsx': r'^\s+(\w+)\s*\(',
            '.tsx': r'^\s+(?:public|private|protected)?\s*(\w+)\s*\(',
            '.java': r'^\s+(?:public|private|protected)\s+\w+\s+(\w+)\s*\(',
            '.cs': r'^\s+(?:public|private|protected)\s+\w+\s+(\w+)\s*\(',
            '.cpp': r'^\s+\w+\s+(\w+)\s*\(',
            '.swift': r'^\s+func\s+(\w+)\s*\(',
            '.kt': r'^\s+fun\s+(\w+)\s*\(',
            '.rb': r'^\s+def\s+(\w+)',
            '.php': r'^\s+(?:public|private|protected)?\s+function\s+(\w+)\s*\(',
        }

        pattern = method_patterns.get(ext)
        if pattern:
            matches = re.findall(pattern, content, re.MULTILINE)
            methods = list(set(matches))[:10]

        return methods

    def _extract_functions(self, content: str, ext: str) -> list:
        """Extract function definitions with details"""
        import re
        functions = []

        func_patterns = {
            '.js': r'(?:function|const|let|var)\s+(\w+)\s*=?\s*(?:async\s*)?\(([^)]*)\)\s*(?:=>|{)',
            '.ts': r'(?:function|const|let)\s+(\w+)\s*(?:<[^>]+>)?\s*\(([^)]*)\)\s*:\s*(\w+)',
            '.jsx': r'(?:function|const)\s+(\w+)\s*\(([^)]*)\)',
            '.tsx': r'(?:function|const)\s+(\w+)\s*(?:<[^>]+>)?\s*\(([^)]*)\)',
            '.java': r'(?:public|private|protected)\s+(?:static\s+)?(\w+)\s+(\w+)\s*\(([^)]*)\)',
            '.cs': r'(?:public|private|protected)\s+(?:static\s+)?(\w+)\s+(\w+)\s*\(([^)]*)\)',
            '.go': r'func\s+(\w+)\s*\(([^)]*)\)(?:\s*\(([^)]*)\))?',
            '.rs': r'fn\s+(\w+)\s*\(([^)]*)\)(?:\s*->\s*(\w+))?',
            '.swift': r'func\s+(\w+)\s*\(([^)]*)\)(?:\s*->\s*(\w+))?',
            '.kt': r'fun\s+(\w+)\s*\(([^)]*)\)(?:\s*:\s*(\w+))?',
            '.rb': r'def\s+(\w+)\s*(?:\(([^)]*)\))?',
            '.php': r'function\s+(\w+)\s*\(([^)]*)\)',
            '.cpp': r'(\w+)\s+(\w+)\s*\(([^)]*)\)',
            '.c': r'(\w+)\s+(\w+)\s*\(([^)]*)\)',
        }

        pattern = func_patterns.get(ext)
        if pattern:
            matches = re.findall(pattern, content)
            for match in matches[:15]:
                if isinstance(match, tuple):
                    if ext in ['.java', '.cs', '.cpp', '.c']:
                        func_name = match[1] if len(match) > 1 else match[0]
                        params = match[2] if len(match) > 2 else match[1] if len(match) > 1 else ''
                        return_type = match[0] if len(match) > 2 else None
                    else:
                        func_name = match[0]
                        params = match[1] if len(match) > 1 else ''
                        return_type = match[2] if len(match) > 2 else None
                else:
                    func_name = match
                    params = ''
                    return_type = None

                functions.append({
                    'name': func_name,
                    'params': params.strip() if params else '',
                    'return_type': return_type.strip() if return_type else None,
                    'description': ''
                })

        return functions

    def _extract_constants(self, content: str, ext: str) -> list:
        """Extract constants and global variables"""
        import re
        constants = []

        const_patterns = {
            '.js': r'(?:const|let|var)\s+([A-Z_][A-Z0-9_]*)\s*=',
            '.ts': r'(?:const|let)\s+([A-Z_][A-Z0-9_]*)\s*(?::\s*\w+)?\s*=',
            '.jsx': r'const\s+([A-Z_][A-Z0-9_]*)\s*=',
            '.tsx': r'const\s+([A-Z_][A-Z0-9_]*)\s*=',
            '.java': r'(?:public|private|protected)\s+static\s+final\s+\w+\s+([A-Z_][A-Z0-9_]*)',
            '.cs': r'(?:public|private|protected)\s+const\s+\w+\s+([A-Z_][A-Z0-9_]*)',
            '.go': r'const\s+([A-Z]\w*)',
            '.rs': r'const\s+([A-Z_][A-Z0-9_]*)',
            '.swift': r'let\s+([A-Z_][A-Z0-9_]*)',
            '.kt': r'const\s+val\s+([A-Z_][A-Z0-9_]*)',
            '.rb': r'([A-Z_][A-Z0-9_]*)\s*=',
            '.php': r'define\([\'"]([A-Z_][A-Z0-9_]*)[\'"]',
            '.cpp': r'#define\s+([A-Z_][A-Z0-9_]*)',
            '.c': r'#define\s+([A-Z_][A-Z0-9_]*)',
        }

        pattern = const_patterns.get(ext)
        if pattern:
            matches = re.findall(pattern, content)
            constants = list(set(matches))[:10]

        return constants

    def _generate_file_flow(self, file_path: str) -> str:
        """Generate flow diagram for file (all languages)"""
        try:
            abs_path = self.project_path / file_path
            if not abs_path.exists():
                return ""

            language = abs_path.suffix.lower()

            # Try Python AST first
            if language == '.py':
                try:
                    with open(abs_path, 'r', encoding='utf-8') as f:
                        tree = ast.parse(f.read())

                    functions = [n.name for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)][:10]

                    if not functions:
                        return ""

                    flow = "## 🔄 Function Flow\n\n```mermaid\ngraph TD\n"
                    flow += "    Start[Module Load]\n"

                    for i, func in enumerate(functions):
                        flow += f"    Start --> F{i}[{func}()]\n"

                    flow += "```"

                    return flow
                except:
                    pass

            # Universal flow for all languages
            return self._generate_universal_flow(abs_path)

        except:
            return ""

    def _generate_universal_flow(self, file_path: Path) -> str:
        """Generate basic flow diagram for any language"""
        try:
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()

            import re

            # Find function names using universal patterns
            func_patterns = [
                r'function\s+(\w+)',
                r'def\s+(\w+)',
                r'func\s+(\w+)',
                r'fn\s+(\w+)',
                r'(?:public|private|protected)?\s+\w+\s+(\w+)\s*\(',
            ]

            functions = set()
            for pattern in func_patterns:
                functions.update(re.findall(pattern, content))

            functions = list(functions)[:10]

            if not functions:
                return ""

            flow = "## 🔄 Code Flow\n\n```mermaid\ngraph TD\n"
            flow += "    Start[File Entry]\n"

            for i, func in enumerate(functions):
                flow += f"    Start --> F{i}[{func}()]\n"

            flow += "```"

            return flow

        except:
            return ""

    def _generate_pie_chart_data(self, lang_stats: Dict) -> str:
        """Generate pie chart data for mermaid"""
        lines = []
        for lang, stats in lang_stats.items():
            lines.append(f'    "{lang}" : {stats["code"]}')
        return '\n'.join(lines)

    def _get_badge_color(self, score: float) -> str:
        """Get badge color based on score"""
        if score >= 90:
            return 'brightgreen'
        elif score >= 80:
            return 'green'
        elif score >= 70:
            return 'yellowgreen'
        elif score >= 60:
            return 'yellow'
        else:
            return 'red'


if __name__ == '__main__':
    # Test
    print("README Generator module loaded successfully")
